---
- name: yum install nfs packages
  vars:
    packages:
    - rpcbind
    - nfs-utils
  yum:
    name: "{{ packages }}"
    state: present

- name: "start and enable nfs"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-utils